### ISSUE TITLE
Docker:  html/template:  "home" is undefined

### ISSUE THREAD

**Issue by dmlambea** [gogs/gogs#4996]
- Gogs version (or commit ref): 0.11.34.1122  (image downloaded from Docker Hub)
- Git version:
- Operating system: CoreOS Stable 1576.5.0
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description
First run of the container image (stable, unmodified from Docker Hub) over an existing installation of Gogs (/data volume already containing more than 16000 files) makes some URLs unusable.

Error shown in browser is:  `html/template:  "home" is undefined`.  When logged in, the dashboard works but some other URLs with templates like org/create or admin/dashboard fail with the same error.

Opening a shell into the running container and killing the gogs PID makes Gogs to restart fully functional. But restarting the container from scratch reproduces the problem.

I've noticed that removing the line `chown -R git:git /data /app/gogs ~git/` from /app/gogs/docker/s6/gogs/setup makes the container fully functional in all cases. The Dockerfile used to create the functional container is:

> FROM gogs/gogs:0.11.34
> RUN sed -i 's/^chown/# chown/g' /app/gogs/docker/s6/gogs/setup

...

**Comment by weisd** [comment]
got the same issues

**Comment by wurst-case-scenario** [comment]
same for me

**Comment by seven-tan** [comment]
same for me

**Comment by seven-tan** [comment]
html/template:repo/diff/page:6:14: no such template "repo/commits_table"

**Comment by argent-smith** [comment]
Have the same issue. Also, the first container log lines are:

```
05/04/2018 16:58:01usermod: no changes
05/04/2018 16:58:01init:socat  | Linked container DB will be binded to localhost on port 3306
05/04/2018 16:58:01init:socat  | Can't bind linked container GOGS_MYSQL_1 to localhost, port 3306 already in use
```

**Comment by amit-handa** [comment]
any updates on this ? I am facing same issue 0.11.49.xx gogs docker image.

**Comment by Unknwon** [comment]
Only happens if host is CentOS? I couldn't reproduce on Mac.

**Comment by amit-handa** [comment]
yes, could be. I ran it on rhel 7, it worked. on centos 7, it didnt, so far. strangely.

**Comment by dmlambea** [comment]
My experience is with CoreOS hosts.

**Comment by argent-smith** [comment]
Still an issue. Can we log/debug this somehow?

**Comment by rossigee** [comment]
WTF is the 'chown' doing in there anyway? Just remove it. The permissions are just fine as they are, thank you.

In our case, we have a large set of repos which are mounted via a slow NFS connection. Doing a chown before starting the service causes it to just sits there not providing service for 30 mins or so whenever the container starts up.

**Comment by rossigee** [comment]
PR submitted to remove the rogue 'chown' command. For the impatient, you can pull the `rossigee/gogs`container in the meantime.

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #5390, please help test on `develop` branch (Docker image need few minutes to build).

**Comment by outlookhazy** [comment]
So this was fixed, merged, reverted, then closed? what?
I'm having this issue today with a brand new container.

**Comment by outlookhazy** [comment]
Ok, mine happens to be using a postgresql database like the original ticket if that makes any difference. Likewise, I can use the image he posted with no issue.

**Comment by Unknwon** [comment]
Which database you use shouldn't make difference.

**Comment by skopciewski** [comment]
I also still have a problem with it::
- `CoreOS 1855.4.0`
- `gogs/gogs                    latest              bd66c686064b        6 weeks ago`
- `SQLite`

and as before to run it I need to execute:
```
docker exec -it gogs ps | grep "gogs web"                                                                                                                           
# 28        git       0:00 /app/gogs/gogs web
docker exec -it gogs kill 28
```

**Comment by Unknwon** [comment]
Looks like a CoreOS specific problem?

**Comment by khanzf** [comment]
Was this ever resolved without creating a new container?

**Comment by rossigee** [comment]
@Unknwon - your 'brand new container' must not have much data in it, or that data is not being served from a slow filesystem, so I suspect you are not noticing the problem in the same way that others are.

This bug still appears to exist in recent 'gogs/gogs' builds, and I don't seem to be the only person that has to kill the 'chown' process in the container each time it is restarted.

**Comment by Unknwon** [comment]
@rossigee I'm not good at Bash scripts, but shouldn't `chown` command now only be executed for containers that does not have `app.ini` file in place?

https://github.com/gogs/gogs/blob/798636c95b207fc97a785ce545d7af7197361447/docker/s6/gogs/setup#L22-L25

**Comment by rossigee** [comment]
Yep, @Unknwon - my bad. I just found that patch and realised I was using 'IfNotPresent' (i.e. not the latest image) on my setup. Sorry about that.
