### ISSUE TITLE
Impossible to start latest docker image (7adac94f1e93cc5c3545ea31688662dcef9cd737)

### ISSUE THREAD

**Issue by JulienDlq** [gogs/gogs#7864]
### Gogs version

7adac94f1e93cc5c3545ea31688662dcef9cd737

### Git version

- Server: not able to start the docker image…
- Client: 2.47.1

### Operating system

OpenMediaVault + docker plugin

### Database

SQLite 3

### Describe the bug

Since I pulled the latest docker image (7adac94f1e93cc5c3545ea31688662dcef9cd737), it is not able to start anymore.

### To reproduce

Just pull the latest docker image (7adac94f1e93cc5c3545ea31688662dcef9cd737).

### Expected behavior

The docker image starts and works.

### Additional context

Here are the logs:
```
gogs  | /app/gogs/docker/start.sh: exec: line 80: /bin/s6-svscan: not found
gogs  | usermod: no changes
gogs  | /app/gogs/docker/start.sh: exec: line 80: /bin/s6-svscan: not found

gogs exited with code 0
gogs  | usermod: no changes
gogs  | usermod: no changes
gogs  | /app/gogs/docker/start.sh: exec: line 80: /bin/s6-svscan: not found
gogs  | /app/gogs/docker/start.sh: exec: line 80: /bin/s6-svscan: not found

gogs exited with code 0
gogs  | usermod: no changes
gogs  | /app/gogs/docker/start.sh: exec: line 80: /bin/s6-svscan: not found

gogs exited with code 0
gogs  | usermod: no changes
gogs  | /app/gogs/docker/start.sh: exec: line 80: /bin/s6-svscan: not found

gogs exited with code 127
gogs  | usermod: no changes
gogs  | /app/gogs/docker/start.sh: exec: line 80: /bin/s6-svscan: not found

gogs exited with code 127
gogs  | usermod: no changes
gogs  | /app/gogs/docker/start.sh: exec: line 80: /bin/s6-svscan: not found

gogs exited with code 127
gogs  | usermod: no changes
gogs  | /app/gogs/docker/start.sh: exec: line 80: /bin/s6-svscan: not found
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wilcomir** [comment]
Same issue here. Can anyone suggest a tag to rollback to? I tried to pin tag 0.13 instead of latest, but it is not working for me.

**Comment by digitizer0** [comment]
Same here

**Comment by JordanGreenies** [comment]
same, rollback not working either

**Comment by zlymeda** [comment]
this is how I fixed it:

```bash
$ docker images gogs/gogs
REPOSITORY   TAG       IMAGE ID       CREATED        SIZE
gogs/gogs    latest    0e4dd34ff305   4 hours ago    107MB
gogs/gogs    <none>    4771749beaf6   6 days ago     102MB
gogs/gogs    <none>    cbd97aff7505   12 days ago    99.3MB
gogs/gogs    <none>    c98dbb1b82ef   2 weeks ago    99.3MB
gogs/gogs    <none>    fab7a579851a   5 weeks ago    99.3MB
gogs/gogs    <none>    5a8a12d97c08   6 weeks ago    99.3MB
gogs/gogs    <none>    e4bb68c359cf   6 weeks ago    99.3MB
gogs/gogs    <none>    bc65d553656e   7 weeks ago    99.3MB
gogs/gogs    <none>    1f8f780e9568   2 months ago   99.3MB

$ docker tag 4771749beaf6 gogs/gogs:working

```

and then use the `working` tag.. and I am back to the previous version

**Comment by wilcomir** [comment]
Thanks @zlymeda - unfortunately I do not have older images on my system, they get periodically pruned. I am not sure if we can access an untagged version from the registry - that would be a good solution I guess.

I am also wondering why the docker image is updated so often when the latest release of gogs is a few months old - not complaining, just curious. I'm the one who set up unattended upgrades, and now I pay the price :)

**Comment by JordanGreenies** [comment]
> Thanks @zlymeda - unfortunately I do not have older images on my system, they get periodically pruned. I am not sure if we can access an untagged version from the registry - that would be a good solution I guess.
> 
> I am also wondering why the docker image is updated so often when the latest release of gogs is a few months old - not complaining, just curious. I'm the one who set up unattended upgrades, and now I pay the price :)

I have the same problem

**Comment by wenkeming** [comment]
same. I pull 0.13 as new, it's working for me

**Comment by cryptovaltt** [comment]
There is a bug in latest Dockerfile.
Very last line in it.
It uses /bin/s6-svscan instead of **/usr/bin/s6-svscan**

I've changed the last line in Dockerfile to look like this:
```
CMD ["/usr/bin/s6-svscan", "/app/gogs/docker/s6/"]`
```
Then I've rebuilt the image:
```bash
docker build -t gogs:working -f Dockerfile .
```
and run:
```bash
docker run --name=gogs -p 10022:22 -p 10880:300 -v gogs-data:/data gogs:working
```
Works for me.

**Comment by L1keava** [comment]
Through my observation, I found that the files is missing in /bin . I have a docker image pulled using `docker pull gogs/gogs:latest` from 7 days ago. I hope it helps you.
![image](https://github.com/user-attachments/assets/ded6c4f3-146d-47f7-bf6a-691501399f5e)
![image](https://github.com/user-attachments/assets/8d2fdead-7372-49bf-b2bf-433ff17ac38b)
![image](https://github.com/user-attachments/assets/71cc1ef8-d7a5-432b-9447-6a19f2e673bc)
GDrive Link: [https://drive.google.com/file/d/1g9dkT20VtK0Q3qNUG1FaRgGBJk94oopb/view](url)
Just Using `docker load -i "gogs.tar"`

**Comment by detece** [comment]
> this is how I fixed it:
> 
> ```shell
> $ docker images gogs/gogs
> REPOSITORY   TAG       IMAGE ID       CREATED        SIZE
> gogs/gogs    latest    0e4dd34ff305   4 hours ago    107MB
> gogs/gogs    <none>    4771749beaf6   6 days ago     102MB
> gogs/gogs    <none>    cbd97aff7505   12 days ago    99.3MB
> gogs/gogs    <none>    c98dbb1b82ef   2 weeks ago    99.3MB
> gogs/gogs    <none>    fab7a579851a   5 weeks ago    99.3MB
> gogs/gogs    <none>    5a8a12d97c08   6 weeks ago    99.3MB
> gogs/gogs    <none>    e4bb68c359cf   6 weeks ago    99.3MB
> gogs/gogs    <none>    bc65d553656e   7 weeks ago    99.3MB
> gogs/gogs    <none>    1f8f780e9568   2 months ago   99.3MB
> 
> $ docker tag 4771749beaf6 gogs/gogs:working
> ```
> 
> and then use the `working` tag.. and I am back to the previous version

Same problem here.
I use same commands to launch with older image, thanks !

**Comment by WoBuGs** [comment]
> There is a bug in latest Dockerfile. Very last line in it uses /bin/s6-svscan instead of **/usr**/bin/s6-svscan Most likely it is related to switching to alpine3.21 as a base image.
> 
> I've changed the last line in Dockerfile to look like this:
> 
> ```
> CMD ["/usr/bin/s6-svscan", "/app/gogs/docker/s6/"]`
> ```
> 
> Then I've rebuilt the image:
> 
> ```shell
> docker build -t gogs:working -f Dockerfile .
> ```
> 
> and run:
> 
> ```shell
> docker run --name=gogs -p 10022:22 -p 10880:3000 -v gogs-data:/data gogs:working
> ```
> 
> Works for me.
> 
> Unfortunately I am not allowed to push changed branch, I am not the contributor (know nothing about Go, only C++, Rust and Python). Can someone please create a PR with that change?

Thanks man, I created one here: https://github.com/gogs/gogs/pull/7867!

Note that you could have done it by forking the repo, and the creating a PR from your fork 😉

**Comment by unknwon** [comment]
Thanks everyone for helping this one out 🙏 The latest Docker image should have this problem fixed!

**Comment by featdd** [comment]
Hi, I'm still encountering this issue even with the latest image for 0.13
```
/app/gogs/docker/start.sh: exec: line 80: /bin/s6-svscan: not found
Backup disabled: BACKUP_INTERVAL has not been found
init:crond  | Cron Daemon (crond) will be run as requested by s6
usermod: no changes 
```
I'm running Gogs on a Synology NAS via Docker and just wanted to update from 0.13.0 to 0.13.1

Greetings
Daniel

**Comment by 88nick22** [comment]
> There is a bug in latest Dockerfile. Very last line in it uses /bin/s6-svscan instead of **/usr**/bin/s6-svscan Most likely it is related to switching to alpine3.21 as a base image.
> 
> I've changed the last line in Dockerfile to look like this:
> 
> ```
> CMD ["/usr/bin/s6-svscan", "/app/gogs/docker/s6/"]`
> ```
> 
> Then I've rebuilt the image:
> 
> ```shell
> docker build -t gogs:working -f Dockerfile .
> ```
> 
> and run:
> 
> ```shell
> docker run --name=gogs -p 10022:22 -p 10880:3000 -v gogs-data:/data gogs:working
> ```
> 
> Works for me.
> 
> Unfortunately I am not allowed to push changed branch, I am not the contributor (know nothing about Go, only C++, Rust and Python). Can someone please create a PR with that change?

this works for me, thanks!

**Comment by unknwon** [comment]
@featdd - thanks for the report 🙏  I am working on a new patch release, you can follow the updates in https://github.com/gogs/gogs/issues/7879.

**Comment by featdd** [comment]
Hi @unknwon,

I just pulled the new pushed image, but it still creates the error, even though it's fixed in the code now.

Greetings
Daniel

**Comment by cryptovaltt** [comment]
> Thanks man, I created one here: #7867!
> 
> Note that you could have done it by forking the repo, and the creating a PR from your fork 😉

Thanks @WoBuGs . Good advice, I was not sure that unrelated person could create PRs by forking repo.

**Comment by unknwon** [comment]
Hi @featdd, what _exact commands_ you used to pull and recreate your Gogs container? And what is the image SHA you're seeing locally?

**Comment by wenkeming** [comment]
@unknwon I pulled the latest image, but I'm still encountering the same error.
<img width="584" alt="image" src="https://github.com/user-attachments/assets/e0e7c898-b3d2-4e15-8481-92840f63a8d0" />

<img width="712" alt="image" src="https://github.com/user-attachments/assets/2b0668a6-ad1d-4cf2-b302-d3bf51d0f6f0" />

**Comment by unknwon** [comment]
Hi @wenkeming, what exact commands you use to start/recreate your Gogs container? It looks like `start.sh:80` thinks the caller passed old s6 path. 🤔

**Comment by wenkeming** [comment]
> Hi @wenkeming, what exact commands you use to start/recreate your Gogs container? It looks like `start.sh:80` thinks the caller passed old s6 path. 🤔

Got it. I'll remove the old command `/bin/s6-svscan /app/gogs/docker/s6/`. Thanks!

**Comment by featdd** [comment]
> Hi @featdd, what _exact commands_ you used to pull and recreate your Gogs container? And what is the image SHA you're seeing locally?

Hi @unknwon, I just pulled the image, but even with the latest 0.13 image I get the same error.
I now also tried to clone the repo and completely build it myself, but still the same error, even though it's correct in the "docker/start.sh".

Is the binary path maybe somehow overwritten or something?
I sadly don't even know what this s6-svscan is even necessary for.

Greetings
Daniel

**Comment by featdd** [comment]
Hi @unknwon,

I just planlessly tried around and changed the base image back to `golang:alpine3.17` & `alpine:3.17` and now it seems to work. Maybe this is a bug in the newest alpine image?

The instance I'm running is only for personal use and not critical, so I'll keep this running for now or report any further issues.

Greetings
Daniel

**Comment by wilcomir** [comment]
@featdd it is working for me, are you sure you actually pulled the latest image? what did you exactly do to update your container? I think I had to to `docker compose up --force-recreate` to actually pull the latest image.

**Comment by featdd** [comment]
> @featdd it is working for me, are you sure you actually pulled the latest image? what did you exactly do to update your container? I think I had to to `docker compose up --force-recreate` to actually pull the latest image.

Hi @wilcomir, I didn't use docker compose, I just pulled and compared the hashes. But I also tried to build the image myself and it still didn't work for me. I fixed the issue by reverting the alpine base image back to 3.17 and build it again locally.
Now it seems to be running fine, so maybe there is an issue with s6 and the latest alpine image!?

Greetings
Daniel

**Comment by unknwon** [comment]
Hi @featdd, what exact commands you used to pull and recreate your Gogs container? And it may also be the same as case as in https://github.com/gogs/gogs/issues/7864#issuecomment-2560703074 that the whatever command that is used to start/recreate your Gogs container passed the old s6 binary path?

**Comment by featdd** [comment]
Hi @unknwon,

It was my fault, it now also works with the latest image, sorry for the troubles...

I just had another look, normally I use the GUI provided by Synology DSM and as I tried to figure out the command executed I saw it still had the old `/bin/s6-svscan` path cached. 🤦 

Greetings
Daniel

**Comment by unknwon** [comment]
Ah nice! @featdd, no worries and thanks for confirming the root cause here ❤️
